[package]
name = "arceos-loader"
version = "0.1.0"
edition = "2021"
authors = ["Zoneshiyi <zoneshiyi@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axstd = { workspace = true, optional = true }
